name: IIO Sim

on: [push, pull_request]

jobs:
  specific:
    name: ${{ matrix.rev }}@${{ matrix.repo }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: "torvalds/linux"
            rev: "v4.9"

          - repo: "torvalds/linux"
            rev: "v4.19"

          - repo: "torvalds/linux"
            rev: "v5.9"

          - repo: "torvalds/linux"
            rev: "master"

          - repo: "Xilinx/linux-xlnx"
            rev: "xilinx-v2017.4"

          - repo: "mathworks/xilinx-linux"
            rev: "mathworks_zynq_vision_R21.1.0"

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        uname -a
        sudo apt-get update
        sudo apt-get -y install libelf-dev device-tree-compiler

    - name: Test example Device Tree
      run: |
        dtc -@ -Hboth -I dts -O dtb -o system-user.dtbo system-user.dtsi
        dtc -@ -Hboth -I dtb -O dts -o round-trip.dtsi system-user.dtbo
        echo "==== Round trip output ===="
        cat round-trip.dtsi

    - name: Prepare kernel
      run: |
        git clone --depth 1 --branch "${{ matrix.rev }}" "https://github.com/${{ matrix.repo }}.git" linux
        make -C linux defconfig
        echo "CONFIG_UIO=y" >> linux/.config
        echo "CONFIG_IIO=y" >> linux/.config
        echo "CONFIG_IIO_BUFFER=y" >> linux/.config
        echo "CONFIG_IIO_BUFFER_DMAENGINE=y" >> linux/.config
        make -C linux olddefconfig
        make -C linux modules_prepare

    - name: Build
      run: |
        make KERNELDIR="$PWD/linux"
        /usr/sbin/modinfo *.ko
