name: IIO Sim

on: [push, pull_request]

jobs:
  specific:
    name: With ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["4.9.1", "4.19.1", "5.9.6", "latest"]
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        uname -a
        sudo apt-get update
        sudo apt-get -y install libelf-dev device-tree-compiler

    - name: Test example Device Tree
      run: |
        dtc -@ -Hboth -I dts -O dtb -o system-user.dtbo system-user.dtsi
        dtc -@ -Hboth -I dtb -O dts -o round-trip.dtsi system-user.dtbo
        echo "==== Round trip output ===="
        cat round-trip.dtsi

    - name: Build w/ specific kernel version
      run: |
        install -d linux
        python3 fetch_linux.py ${{ matrix.version }} - | tar -C linux --strip-components=1 -xJ
        make -C linux defconfig
        echo "CONFIG_IIO=y" >> linux/.config
        echo "CONFIG_IIO_BUFFER=y" >> linux/.config
        echo "CONFIG_IIO_BUFFER_DMAENGINE=y" >> linux/.config
        make -C linux olddefconfig
        make -C linux modules_prepare
        make KERNELDIR="$PWD/linux"
        /usr/sbin/modinfo *.ko
